spring.application.name=sub_agent_visual_effects
server.port= 8093

spring.ai.openai.api-key= ${OPENAI_API_KEY}
spring.ai.openai.embedding.model= text-embedding-3-large
spring.ai.openai.responses.options.model= gpt-5.1
spring.ai.openai.chat.enabled= true
spring.ai.openai.chat.options.model= gpt-5.1
spring.ai.openai.chat.options.temperature=1.0

event.name.image= new-image
logging.level.org.springframework.http.codec=DEBUG

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
